name = "SQLinLean"
version = "0.1.0"
defaultTargets = ["sqlinlean"]

[[lean_lib]]
name = "SQLinLean"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "sqlinlean"
root = "Main"

[[lean_exe]]
name = "tests"
root = "Tests"
